/* 
 * File:	C:\Users\rwahyudi\Projects\ECP_Project\MAX78K\MICCANVAS_SS+_BEAMFORM_ADAU146xSchematic_0_PARAM.h
 * Created:	Tuesday, 09 June 2026 14:14 PM
 * Description:	ADAU146xSchematic_0 parameter RAM definitions.
 * 
 * This software is distributed in the hope that it will be useful, 
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * 
 * This software may only be used to program products purchased from 
 * Analog Devices for incorporation by you into audio products that 
 * are intended for resale to audio product end users.This software 
 * may not be distributed whole or in any part to third parties. 
 * 
 * Copyright © 2026 Analog Devices, Inc. All rights reserved.
 */
#ifndef __MICCANVAS_SS+_BEAMFORM_ADAU146XSCHEMATIC_0_PARAM_H__
#define __MICCANVAS_SS+_BEAMFORM_ADAU146XSCHEMATIC_0_PARAM_H__

/* Module Safeload - Schematic Params */
#define MOD_SAFELOAD_COUNT                          8
#define MOD_SAFELOAD_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_SAFELOAD_DATA_SAFELOAD0_ADDR            24576
#define MOD_SAFELOAD_DATA_SAFELOAD0_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD1_ADDR            24577
#define MOD_SAFELOAD_DATA_SAFELOAD1_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD2_ADDR            24578
#define MOD_SAFELOAD_DATA_SAFELOAD2_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD3_ADDR            24579
#define MOD_SAFELOAD_DATA_SAFELOAD3_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD4_ADDR            24580
#define MOD_SAFELOAD_DATA_SAFELOAD4_MEM_PAGE        0
#define MOD_SAFELOAD_ADDR_SAFELOAD_ADDR             24581
#define MOD_SAFELOAD_ADDR_SAFELOAD_MEM_PAGE         0
#define MOD_SAFELOAD_NUM_SAFELOAD_LOWER_ADDR        24582
#define MOD_SAFELOAD_NUM_SAFELOAD_LOWER_MEM_PAGE    0
#define MOD_SAFELOAD_NUM_SAFELOAD_UPPER_ADDR        24583
#define MOD_SAFELOAD_NUM_SAFELOAD_UPPER_MEM_PAGE    0



/* Module FractionalDelay_0 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_COUNT                          2
#define MOD_FRACTIONALDELAY_0_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_ADDR           49
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_FIXPT          0x0059930C
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.3499)
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_MAXDELAY_ADDR                  48
#define MOD_FRACTIONALDELAY_0_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_MAXDELAY_MEM_PAGE              0


/* Module FractionalDelay_0_1 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_1_COUNT                          2
#define MOD_FRACTIONALDELAY_0_1_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_ADDR           47
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_FIXPT          0x0098E219
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.5972)
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_1_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_ADDR                  46
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_1_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_2 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_2_COUNT                          2
#define MOD_FRACTIONALDELAY_0_2_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_ADDR           45
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_FIXPT          0x00B31F8A
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.6997)
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_2_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_ADDR                  44
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_2_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_3 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_3_COUNT                          2
#define MOD_FRACTIONALDELAY_0_3_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_ADDR           43
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_FIXPT          0x0098E219
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.5972)
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_3_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_ADDR                  42
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_3_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_4 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_4_COUNT                          2
#define MOD_FRACTIONALDELAY_0_4_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_ADDR           41
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_FIXPT          0x0059930C
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.3499)
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_4_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_ADDR                  40
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_4_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_5 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_5_COUNT                          2
#define MOD_FRACTIONALDELAY_0_5_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_ADDR           39
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_FIXPT          0x001A3D71
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.1025)
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_5_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_ADDR                  38
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_5_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_6 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_6_COUNT                          2
#define MOD_FRACTIONALDELAY_0_6_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_ADDR           37
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_FIXPT          0x00000000
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_6_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_ADDR                  36
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_6_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_7 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_7_COUNT                          2
#define MOD_FRACTIONALDELAY_0_7_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_ADDR           35
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_FIXPT          0x001A3D71
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.1025)
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_7_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_ADDR                  34
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_7_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_8 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_8_COUNT                          2
#define MOD_FRACTIONALDELAY_0_8_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_ADDR           33
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_FIXPT          0x00432CA5
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.2624)
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_8_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_ADDR                  32
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_8_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_9 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_9_COUNT                          2
#define MOD_FRACTIONALDELAY_0_9_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_ADDR           31
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_FIXPT          0x006FF2E5
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.4373)
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_9_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_ADDR                  30
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_9_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_10 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_10_COUNT                          2
#define MOD_FRACTIONALDELAY_0_10_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_ADDR           29
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_FIXPT          0x0086594B
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.5248)
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_10_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_ADDR                  28
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_10_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_11 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_11_COUNT                          2
#define MOD_FRACTIONALDELAY_0_11_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_ADDR           27
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_FIXPT          0x006FF2E5
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.4373)
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_11_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_ADDR                  26
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_11_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_12 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_12_COUNT                          2
#define MOD_FRACTIONALDELAY_0_12_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_ADDR           25
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_FIXPT          0x00432CA5
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.2624)
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_12_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_ADDR                  24
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_12_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_13 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_13_COUNT                          2
#define MOD_FRACTIONALDELAY_0_13_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_ADDR           23
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_FIXPT          0x002CC63F
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.1749)
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_13_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_ADDR                  22
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_13_MAXDELAY_MEM_PAGE              0

/* Module FractionalDelay_0_14 - Fractional Delay */
#define MOD_FRACTIONALDELAY_0_14_COUNT                          2
#define MOD_FRACTIONALDELAY_0_14_SCHEMATIC                      "ADAU146xSchematic_0"
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_ADDR           21
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_FIXPT          0x0059930C
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.3499)
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_DATA_MEMORY    "DM0"
#define MOD_FRACTIONALDELAY_0_14_DELAYPERCENTAGE_MEM_PAGE       0
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_ADDR                  20
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_FIXPT                 0x00000008
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(8)
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_MEM_PAGE              0
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_DATA_MEMORY           "DM0"
#define MOD_FRACTIONALDELAY_0_14_MAXDELAY_MEM_PAGE              0

/* Module SignalEnvelope_0 - RMS Envelope */
#define MOD_SIGNALENVELOPE_0_COUNT                      3
#define MOD_SIGNALENVELOPE_0_SCHEMATIC                  "ADAU146xSchematic_0"
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_ADDR           51
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_FIXPT          0x00013B23
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.00480857655249389)
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_DATA_MEMORY    "DM0"
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_MEM_PAGE       0
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_DATA_MEMORY    "DM0"
#define MOD_SIGNALENVELOPE_0_RMSTCINDBPS_MEM_PAGE       0
#define MOD_SIGNALENVELOPE_0_DECAY_ADDR                 53
#define MOD_SIGNALENVELOPE_0_DECAY_FIXPT                0x00000E39
#define MOD_SIGNALENVELOPE_0_DECAY_VALUE                SIGMASTUDIOTYPE_8_24_CONVERT(0.000217013888888889)
#define MOD_SIGNALENVELOPE_0_DECAY_TYPE                 SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALENVELOPE_0_DECAY_DATA_MEMORY          "DM0"
#define MOD_SIGNALENVELOPE_0_DECAY_MEM_PAGE             0
#define MOD_SIGNALENVELOPE_0_DECAY_DATA_MEMORY          "DM0"
#define MOD_SIGNALENVELOPE_0_DECAY_MEM_PAGE             0
#define MOD_SIGNALENVELOPE_0_HOLD_ADDR                  52
#define MOD_SIGNALENVELOPE_0_HOLD_FIXPT                 0x00000000
#define MOD_SIGNALENVELOPE_0_HOLD_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_SIGNALENVELOPE_0_HOLD_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_SIGNALENVELOPE_0_HOLD_DATA_MEMORY           "DM0"
#define MOD_SIGNALENVELOPE_0_HOLD_MEM_PAGE              0
#define MOD_SIGNALENVELOPE_0_HOLD_DATA_MEMORY           "DM0"
#define MOD_SIGNALENVELOPE_0_HOLD_MEM_PAGE              0

/* Module SingleLevelDetector_0 - Single Band Level Detector (Direct Read) */
#define MOD_SINGLELEVELDETECTOR_0_COUNT                1
#define MOD_SINGLELEVELDETECTOR_0_SCHEMATIC            "ADAU146xSchematic_0"
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_ADDR           50
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_FIXPT          0x01000000
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_DATA_MEMORY    "DM0"
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_MEM_PAGE       0
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_DATA_MEMORY    "DM0"
#define MOD_SINGLELEVELDETECTOR_0_LEVEL_MEM_PAGE       0

#endif
