"""One-off: rename live* UI ids to sim* in array_explorer.html."""
from pathlib import Path

p = Path(__file__).resolve().parents[1] / "results" / "array_explorer.html"
t = p.read_text(encoding="utf-8")
repls = [
    ("Live Sim", "Simulator"),
    ("btnLive", "btnSimulator"),
    ("liveControls", "simControls"),
    ("live-basic", "sim-basic"),
    ("liveGeoRow", "simGeoRow"),
    ("liveBeamMethodRow", "simBeamMethodRow"),
    ("liveBeamMethod", "simBeamMethod"),
    ("liveScanAnglesRow", "simScanAnglesRow"),
    ("liveScanAngles", "simScanAngles"),
    ("liveBeamKRow", "simBeamKRow"),
    ("liveBeamKVal", "simBeamKVal"),
    ("liveBeamK", "simBeamK"),
    ("liveMicCountRow", "simMicCountRow"),
    ("liveMicCount", "simMicCount"),
    ("liveMicVal", "simMicVal"),
    ("liveRadiusRow", "simRadiusRow"),
    ("liveRadVal", "simRadVal"),
    ("liveRadius", "simRadius"),
    ("liveSepRow", "simSepRow"),
    ("liveSepVal", "simSepVal"),
    ("liveSep", "simSep"),
    ("liveRoomLVal", "simRoomLVal"),
    ("liveRoomL", "simRoomL"),
    ("liveRoomWVal", "simRoomWVal"),
    ("liveRoomW", "simRoomW"),
    ("liveRoomHVal", "simRoomHVal"),
    ("liveRoomH", "simRoomH"),
    ("liveRT60Val", "simRT60Val"),
    ("liveRT60", "simRT60"),
    ("liveSrcAzVal", "simSrcAzVal"),
    ("liveSrcAz", "simSrcAz"),
    ("liveSrcElVal", "simSrcElVal"),
    ("liveSrcEl", "simSrcEl"),
    ("liveSrcDistVal", "simSrcDistVal"),
    ("liveSrcDist", "simSrcDist"),
    ("liveDroneSPLVal", "simDroneSPLVal"),
    ("liveDroneSPL", "simDroneSPL"),
    ("liveCrowdSPLVal", "simCrowdSPLVal"),
    ("liveCrowdSPL", "simCrowdSPL"),
    ("livePASPLVal", "simPASPLVal"),
    ("livePASPL", "simPASPL"),
    ("liveMicFloorVal", "simMicFloorVal"),
    ("liveMicFloor", "simMicFloor"),
    ("liveSeedVal", "simSeedVal"),
    ("liveRandSeed", "simRandSeed"),
    ("liveSeed", "simSeed"),
    ("liveCrowdModel", "simCrowdModel"),
    ("liveCrowdVal", "simCrowdVal"),
    ("liveCrowd", "simCrowd"),
    ("livePAVal", "simPAVal"),
    ("livePA", "simPA"),
    ("liveIntVal", "simIntVal"),
    ("liveInt", "simInt"),
    ("liveDiffuse", "simDiffuse"),
    ("liveMismatch", "simMismatch"),
    ("liveCrosstalkDbVal", "simCrosstalkDbVal"),
    ("liveCrosstalkDb", "simCrosstalkDb"),
    ("liveCrosstalkModel", "simCrosstalkModel"),
    ("liveCrosstalkCornerLabel", "simCrosstalkCornerLabel"),
    ("liveCrosstalkCornerVal", "simCrosstalkCornerVal"),
    ("liveCrosstalkCorner", "simCrosstalkCorner"),
    ("liveCrosstalk", "simCrosstalk"),
    ("liveQuant", "simQuant"),
    ("liveBitDepth", "simBitDepth"),
    ("liveTempGradVal", "simTempGradVal"),
    ("liveTempGrad", "simTempGrad"),
    ("liveHumidityVal", "simHumidityVal"),
    ("liveHumidity", "simHumidity"),
    ("liveTempVal", "simTempVal"),
    ("liveTemp", "simTemp"),
    ("liveMoving", "simMoving"),
    ("liveTrajType", "simTrajType"),
    ("liveHeadingLabel", "simHeadingLabel"),
    ("liveHeadingVal", "simHeadingVal"),
    ("liveHeading", "simHeading"),
    ("liveSpeedVal", "simSpeedVal"),
    ("liveSpeed", "simSpeed"),
    ("liveChunksVal", "simChunksVal"),
    ("liveChunks", "simChunks"),
    ("liveNPlaneWavesVal", "simNPlaneWavesVal"),
    ("liveNPlaneWaves", "simNPlaneWaves"),
    ("liveMlPreview", "simMlPreview"),
    ("liveMlFeatBitDepth", "simMlFeatBitDepth"),
    ("liveMlBitDepth", "simMlBitDepth"),
    ("liveMlNMelsVal", "simMlNMelsVal"),
    ("liveMlNMels", "simMlNMels"),
    ("liveFundamentalVal", "simFundamentalVal"),
    ("liveFundamental", "simFundamental"),
    ("liveHarmonicComb", "simHarmonicComb"),
    ("liveFmaxVal", "simFmaxVal"),
    ("liveFmax", "simFmax"),
    ("liveFminVal", "simFminVal"),
    ("liveFmin", "simFmin"),
    ("liveNormalizeAudio", "simNormalizeAudio"),
    ("liveFracMaxVal", "simFracMaxVal"),
    ("liveFracMax", "simFracMax"),
    ("liveFracTapsVal", "simFracTapsVal"),
    ("liveFracTaps", "simFracTaps"),
    ("liveTargetFsVal", "simTargetFsVal"),
    ("liveTargetFs", "simTargetFs"),
    ("liveAdvanced", "simAdvanced"),
    ("liveGeo", "simGeo"),
    ("runLiveSimulation", "runOneShotSimulation"),
    ("setMode('live')", "setMode('sim')"),
    ("mode === 'live'", "mode === 'sim'"),
    ("m === 'live'", "m === 'sim'"),
    ("#liveControls", "#simControls"),
    ("liveSliders", "simSliders"),
    ("liveScanAngles", "simScanAngles"),
]
for a, b in repls:
    t = t.replace(a, b)
p.write_text(t, encoding="utf-8")
print("remaining liveGeo:", t.count("liveGeo"))
